spring.application.name=EventBookingSystem

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/eventbookingsystem
spring.datasource.username=root
spring.datasource.password=root
server.port=8084


#spring.security.user.name=karthik
#spring.security.user.password=123345
